fix(job): fix empty job log
glpi-project/glpi-inventory-plugin pull request #137
Opened 2022-06-21 12:35 UTC by stonebuzz

Before (nothing display)

![image](https://user-images.githubusercontent.com/7335054/174800098-f9659adb-3976-416c-b8f6-8c94fbc0dfe8.png)

After

![image](https://user-images.githubusercontent.com/7335054/174800180-08c5adf2-c5c7-4e97-aef5-875b7bb6ef2c.png)

2022-06-21 12:38 UTC, cedric-anne approved these changes

2022-06-21 12:47 UTC, trasher approved these changes

2022-06-21 15:12 UTC, g-bougard approved these changes

2022-06-22 06:45 UTC, g-bougard requested changes
Finally, it seems to have a side-effect on the tasks shown from the ip range entries: all tasks are shown there where only tasks using the ip range should be.

2022-06-22 15:57 UTC, g-bougard commented on inc/task.class.php
> +
It seems this blank line makes lint fail.
```suggestion
```

2022-06-22 16:03 UTC, g-bougard approved these changes

2022-06-23 05:28 UTC, trasher approved these changes

2022-06-23 05:46 UTC, trasher commented on inc/task.class.php
> +
```suggestion
```

2022-06-23 06:16 UTC, orthagh approved these changes

2022-06-23 09:05 UTC, merged