Some dark theme fixes
glpi-project/glpi-inventory-plugin pull request #155
Opened 2022-06-24 01:28 UTC by cconard96

Fix some color issues with dark themes in the task management section.

2022-06-24 06:10 UTC, trasher approved these changes

2022-06-24 06:10 UTC, trasher commented on inc/taskjobview.class.php
> +                            __('Cancel modifications', 'glpiinventory') ."</button>
```suggestion
                            __('Cancel modifications', 'glpiinventory') . "</button>
```

2022-06-24 06:27 UTC, stonebuzz requested changes
Hi @cconard96 can you base PR on ```develop``` branch ?

2022-06-24 08:29 UTC, stonebuzz commented
need to be rebased

2022-06-27 12:56 UTC, cedric-anne approved these changes

2022-06-27 13:00 UTC, orthagh approved these changes

2022-06-27 14:04 UTC, merged