fix(core): replace with GLPI-Agent
glpi-project/glpi-inventory-plugin pull request #339
Opened 2023-04-04 13:19 UTC by stonebuzz

fix(core): replace with GLPI-Agent

2023-04-04 13:22 UTC, g-bougard requested changes
Indeed GLPI-Agent 2.3.20 & GLPI-Agent 2.3.21 don't exist.
You should probably change text to tell to use GLPI-Agent or FIA with the given versions.

2023-04-04 13:29 UTC, stonebuzz commented
> Indeed GLPI-Agent 2.3.20 & GLPI-Agent 2.3.21 don't exist. You should probably change text to tell to use GLPI-Agent or FIA with the given versions.

done =)

2023-04-04 14:11 UTC, cedric-anne requested changes
Lots of messages are not using the `glpiinventory` translation domain, it should be fixed.

2023-04-04 14:11 UTC, cedric-anne commented on inc/deployaction.class.php
> +            echo __('GLPI-gent or Fusioninventory-Agent >= 2.3.20 mandatory');
```suggestion
            echo __('GLPI-Agent or Fusioninventory-Agent >= 2.3.20 mandatory', 'glpiinventory');
```

2023-04-04 14:11 UTC, cedric-anne commented on inc/deploycheck.class.php
> +                $values['path_comment']    = __('Example of registry key') . ': HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent\\';
```suggestion
                $values['path_comment']    = __('Example of registry key', 'glpiinventory') . ': HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent\\';
```

2023-04-04 14:11 UTC, cedric-anne commented on inc/deploycheck.class.php
> +                $values['warning_message'] = sprintf(__('GLPI-Agent or Fusioninventory-Agent >= %1s recommended'), '2.3.20');
```suggestion
                $values['warning_message'] = sprintf(__('GLPI-Agent or Fusioninventory-Agent >= %1s recommended', 'glpiinventory'), '2.3.20');
```

2023-04-04 14:11 UTC, cedric-anne commented on inc/deploycheck.class.php
> +                $values['path_comment']    = __('Example of registry value') . ': HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent\server';
```suggestion
                $values['path_comment']    = __('Example of registry value', 'glpiinventory') . ': HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent\server';
```

2023-04-05 07:11 UTC, g-bougard approved these changes

2023-04-05 07:15 UTC, cedric-anne commented on inc/deployaction.class.php
> +            echo __('GLPI-Agent or Fusioninventory-Agent >= 2.3.20 mandatory', 'glpiinventory');
```suggestion
            echo sprintf(__('GLPI-Agent or Fusioninventory-Agent >= %1s mandatory', 'glpiinventory'), '2.3.20');
```

2023-04-05 08:07 UTC, merged