Drop WOL
glpi-project/glpi-inventory-plugin pull request #390
Opened 2023-08-10 12:52 UTC by trasher

2023-08-10 12:53 UTC, trasher commented
There is certainly a migration part to add to finish that removal; let's see if tests are OK already.

2023-09-25 08:27 UTC, cedric-anne approved these changes

2023-09-25 08:43 UTC, stonebuzz requested changes

2023-09-25 08:43 UTC, stonebuzz commented on hook.php
> -        $sopt[5165]['massiveaction'] = false;
Should be removed from ```glpi_displaypreferences``` ?

2023-09-25 09:01 UTC, cedric-anne approved these changes

2023-09-25 09:02 UTC, trasher commented on hook.php
> -        $sopt[5165]['massiveaction'] = false;
done in last commit

2023-09-25 09:08 UTC, stonebuzz approved these changes

2023-10-02 11:28 UTC, merged