communication column has been dropped from takss table 10 years ago
glpi-project/glpi-inventory-plugin pull request #445
Opened 2023-11-22 14:20 UTC by trasher

see https://github.com/glpi-project/glpi-inventory-plugin/commit/d52f37fa927a582bfad4a39288fd9447bb324ccb

2023-11-22 14:24 UTC, cedric-anne approved these changes

2023-11-22 14:38 UTC, cedric-anne requested changes
See comment.

2023-11-22 14:39 UTC, cedric-anne commented on inc/networkinventory.class.php
> +    public function getAgentsSubnet($nb_computers, $subnet = '', $ipstart = '', $ipend = '')
I was wrong, see next comment.

2023-11-23 09:11 UTC, trasher commented on inc/networkinventory.class.php
> -                }
Hum... This part of code relies on `isAgentAlive()` method which has been removed 10 years ago as well... This whole method seems never called IRL.

2023-11-27 08:59 UTC, cedric-anne approved these changes
Seems OK.

2023-12-12 07:03 UTC, merged