Display all computers details for dynamics group
glpi-project/glpi-inventory-plugin pull request #515
Opened 2024-06-05 08:04 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33174

On the basic group page, the only information displayed is the group name and status, but it's true that it was nicer and more practical to display all the information.

**Before**
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/107540223/7b1c0ad9-f834-4386-ab4b-f23288cc02b4)

**After**
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/107540223/9d2f2c28-3e70-4db1-bf2f-ec00552b6abf)

2024-06-06 08:43 UTC, stonebuzz requested changes

2024-06-06 08:43 UTC, stonebuzz commented on inc/deploygroup_dynamicdata.class.php
extra empty line can be removed

2024-06-06 14:23 UTC, trasher commented
@stonebuzz if that is good for you, we can ask customer a validation (I cannot really test on my side).

2024-06-07 10:11 UTC, stonebuzz approved these changes

2024-06-07 11:23 UTC, trasher approved these changes

2024-06-07 11:23 UTC, merged