Encrypt credentials
glpi-project/glpi-inventory-plugin pull request #535
Opened 2024-07-26 08:29 UTC by AdrienClairembault

!33920

2024-07-26 12:57 UTC, Rom1-B requested changes

2024-07-26 12:57 UTC, Rom1-B commented on install/update.php
> +
`$date` is not used
```suggestion
```

2024-07-29 06:07 UTC, trasher approved these changes

2024-07-29 06:09 UTC, Rom1-B approved these changes

2024-07-29 06:14 UTC, cedric-anne approved these changes

2024-07-29 06:40 UTC, merged